// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxfpgdxpigfcqfydurov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4ZnBnZHhwaWdmY3FmeWR1cm92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMjUyNDgsImV4cCI6MjA2MjYwMTI0OH0.cEb5Dy3b1UqjdUS3MIh4Ev83sLYr51lvuYmUvvdoFGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);