// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckiicaqieuoincwtzjky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNraWljYXFpZXVvaW5jd3R6amt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MDQ1OTEsImV4cCI6MjA1NjM4MDU5MX0.F9uC8URep_7Y-_Di4BoaiqjJkvZX8V-MVNhZqkzL3LQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);